import Head from 'next/head'
import Navbarhome from '../Components/Navbar/Navbar'
import 'bootstrap/dist/css/bootstrap.min.css';
import Carouselhome from '../Components/Carousel/Carousel';
import 'mdb-react-ui-kit/dist/css/mdb.min.css'
import { HeroBullets } from '../Components/Content/Content';
import { UserCardImage } from '../Components/Usercard/Usercard';
import Footerhome from '../Components/Footer/Footer';
import Services from '../Components/Services/Services';

export default function Home() {
  return (
    <>
      <Head>
        <title>Krishi Urja</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbarhome />
      <Carouselhome />
      <HeroBullets />
      <Services />
      {/* <UserCardImage /> */}
      {/* <FeaturesImages /> */}
      <Footerhome />
    </>
  )
}
