import Head from 'next/head'
import Image from 'next/image'
import Navbarhome from '../Components/Navbar/Navbar'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import Carouselhome from '../Components/Carousel/Carousel';
import Loginhome from '../Components/Login/Login';
import 'mdb-react-ui-kit/dist/css/mdb.min.css'
import Footer from '../Components/Footer/Footer';
import { HeroBullets } from '../Components/Content/Content';
import { FeaturesImages } from '../Components/Testi/Testi';
import { UserCardImage } from '../Components/Usercard/Usercard';

export default function Home() {
  return (
    <>
      <Head>
        <title>Krishi Urja</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbarhome />
      <Carouselhome />
      <HeroBullets />
      <UserCardImage />
      {/* <FeaturesImages /> */}
      <Footer />
    </>
  )
}
