import Head from 'next/head'
import Navbarhome from '../Components/Navbar/Navbar'
import 'bootstrap/dist/css/bootstrap.min.css';
import React from 'react';
import Register from '../Components/Register/Register.jsx';

function Registerpage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbarhome />
      <Register />
    </>
  )
}

export default Registerpage;